version: "3.7"

services:
    gitserver:
        container_name: gitserver
        image: gitserver:1.0.0
        restart: always
        entrypoint: /usr/local/bin/docker-entrypoint.sh
        ports:
            - "127.0.0.1:50022:22/tcp"
        networks:
            devcicd_net:
                external: true
                aliases:
                    - "gitserver"
        hostname: "gitserver"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "d:/gitserver/gitserver:/opt/gitrepos"

networks:
    devcicd_net:
        external: true
        driver: bridge
